// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwra40526oMi9h-o-CGV-wQZNHXacIvQ',
    appId: '1:108785569147:web:e0e5879bb89d9f4c0401de',
    messagingSenderId: '108785569147',
    projectId: 'nourish-me-428412',
    authDomain: 'nourish-me-428412.firebaseapp.com',
    storageBucket: 'nourish-me-428412.appspot.com',
    measurementId: 'G-7WX6YSECBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPgGACsVsRGApm1OhdJ0ZLX7Ff8dR_20',
    appId: '1:108785569147:android:49efe70f578c289a0401de',
    messagingSenderId: '108785569147',
    projectId: 'nourish-me-428412',
    storageBucket: 'nourish-me-428412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmPYgPGuLCeW682Ry2I6jDq3WCKjV6hg0',
    appId: '1:108785569147:ios:de52e556dcf8d9230401de',
    messagingSenderId: '108785569147',
    projectId: 'nourish-me-428412',
    storageBucket: 'nourish-me-428412.appspot.com',
    androidClientId: '108785569147-np5mvo5aep99j552lqnle8rh80l0cnhc.apps.googleusercontent.com',
    iosClientId: '108785569147-h07u8v7nkof0kl21oamopo98hqi8ts2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nourishMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmPYgPGuLCeW682Ry2I6jDq3WCKjV6hg0',
    appId: '1:108785569147:ios:de52e556dcf8d9230401de',
    messagingSenderId: '108785569147',
    projectId: 'nourish-me-428412',
    storageBucket: 'nourish-me-428412.appspot.com',
    androidClientId: '108785569147-np5mvo5aep99j552lqnle8rh80l0cnhc.apps.googleusercontent.com',
    iosClientId: '108785569147-h07u8v7nkof0kl21oamopo98hqi8ts2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nourishMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFwra40526oMi9h-o-CGV-wQZNHXacIvQ',
    appId: '1:108785569147:web:704cb58a9eed14160401de',
    messagingSenderId: '108785569147',
    projectId: 'nourish-me-428412',
    authDomain: 'nourish-me-428412.firebaseapp.com',
    storageBucket: 'nourish-me-428412.appspot.com',
    measurementId: 'G-QRT61KHX92',
  );
}
